name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Otorgar permisos de ejecución a mvnw
      run: chmod +x mvnw
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
          java-version: '17'
          distribution: 'adopt'
    - name: Build and test
      run: mvn -B package --file pom.xml
    - name: Build the Docker image
      run: |
        docker build -t testdevsu:prod .
        docker tag testdevsu:prod elizabethsariu/testdevsu:prod
        docker push elizabethsariu/testdevsu:prod
